---

ansible_port                 : 22
ansible_ssh_private_key_file : /home/sargis/ubuntu/.ssh/########.pem
owner                        : sargis
environment                  : linux
zabbix_version               : 5.0

...
