---

 - hosts : zabbix_server
   tasks:
     - name : Getting zabbix repository
       uri:
         url : https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+bionic_all.deb
         dest : /opt/zabbix-release_{{ zabbix_version }}-1+bionic_all.deb
         force : false
       become : true

     - name: Installing zabbix repository
       apt :
         deb : /opt/zabbix-release_{{ zabbix_version }}-1+bionic_all.deb
         state : present
       become : true

     - name : Installing zabbix server, proxy-mysql and web-interface
       apt:
         name : '{{ item }}'
         state : present
       become : true
       notify : Starting zabbix server
       loop:
         - zabbix-server-mysql
         - zabbix-proxy-mysql
         - zabbix-frontend-php


   handlers :
     - name : Starting zabbix server
       service :
         name : zabbix-agent
         state : started
       become : true

...

